"""The standard 3D Gaussian Splatting PLY layout.

Readable by SuperSplat, the INRIA viewers, gsplat, Nerfstudio, Unity/Unreal
3DGS plugins and most splat tools::

    x y z nx ny nz f_dc_0..2 f_rest_0..M opacity scale_0..2 rot_0..3

All float32, binary little endian. Values are stored un-activated (log
scale, logit opacity, raw quaternion, SH coefficients), f_rest channel-major.
"""

from pathlib import Path

import numpy as np
import torch


def _attributes(n_rest):
    names = ["x", "y", "z", "nx", "ny", "nz", "f_dc_0", "f_dc_1", "f_dc_2"]
    names += [f"f_rest_{i}" for i in range(n_rest)]
    names += ["opacity", "scale_0", "scale_1", "scale_2", "rot_0", "rot_1", "rot_2", "rot_3"]
    return names


def write_ply(params, path):
    p = {k: (v.detach().cpu().float().numpy() if torch.is_tensor(v) else np.asarray(v, np.float32))
         for k, v in params.items()}
    n = p["means"].shape[0]
    rest = p["shN"].transpose(0, 2, 1).reshape(n, -1)       # channel-major
    columns = [p["means"], np.zeros((n, 3), np.float32), p["sh0"].reshape(n, 3), rest,
               p["opacities"].reshape(n, 1), p["scales"], p["quats"]]
    data = np.concatenate(columns, axis=1).astype("<f4")
    names = _attributes(rest.shape[1])
    header = "ply\nformat binary_little_endian 1.0\n"
    header += "comment Generated by SplatGen\n"
    header += f"element vertex {n}\n"
    header += "".join(f"property float {name}\n" for name in names)
    header += "end_header\n"
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    pending = path.with_suffix(".tmp")
    with open(pending, "wb") as handle:
        handle.write(header.encode("ascii"))
        handle.write(data.tobytes())
    pending.replace(path)
    return path


_PLY_TYPES = {"float": "<f4", "float32": "<f4", "double": "<f8", "float64": "<f8",
              "uchar": "u1", "uint8": "u1", "char": "i1", "int8": "i1",
              "short": "<i2", "int16": "<i2", "ushort": "<u2", "uint16": "<u2",
              "int": "<i4", "int32": "<i4", "uint": "<u4", "uint32": "<u4"}


def read_ply(path):
    """Gaussian parameters from a 3DGS PLY (any SH degree)."""
    raw = Path(path).read_bytes()
    end = raw.index(b"end_header\n") + len(b"end_header\n")
    header = raw[:end].decode("ascii", errors="replace").splitlines()
    if "binary_little_endian" not in " ".join(header):
        raise ValueError("Only binary little-endian PLY files are supported")
    count, props, in_vertex = 0, [], False
    for line in header:
        parts = line.split()
        if parts[:2] == ["element", "vertex"]:
            count, in_vertex = int(parts[2]), True
        elif parts[:1] == ["element"]:
            in_vertex = False
        elif parts[:1] == ["property"] and in_vertex:
            props.append((parts[2], _PLY_TYPES[parts[1]]))
    data = np.frombuffer(raw[end:], dtype=np.dtype(props), count=count)
    names = set(data.dtype.names)
    for required in ("x", "opacity", "scale_0", "rot_0", "f_dc_0"):
        if required not in names:
            raise ValueError(f"Not a Gaussian splat PLY (missing '{required}')")
    col = lambda *keys: np.stack([data[k].astype(np.float32) for k in keys], axis=1)
    n_rest = len([k for k in names if k.startswith("f_rest_")])
    rest = (col(*[f"f_rest_{i}" for i in range(n_rest)]) if n_rest
            else np.zeros((count, 0), np.float32))
    shN = rest.reshape(count, 3, n_rest // 3).transpose(0, 2, 1) if n_rest else np.zeros((count, 0, 3), np.float32)
    return {
        "means": torch.from_numpy(col("x", "y", "z")),
        "scales": torch.from_numpy(col("scale_0", "scale_1", "scale_2")),
        "quats": torch.from_numpy(col("rot_0", "rot_1", "rot_2", "rot_3")),
        "opacities": torch.from_numpy(data["opacity"].astype(np.float32).copy()),
        "sh0": torch.from_numpy(col("f_dc_0", "f_dc_1", "f_dc_2")).unsqueeze(1),
        "shN": torch.from_numpy(np.ascontiguousarray(shN)),
    }
